### ISSUE TITLE
DAOWO

### ISSUE THREAD

**Issue by robmyers** [obxium/awesome-crypto-art#6]
Heya.

I'd like to add this site:

http://www.daowo.org/

which is a resource for a series of shows, workshops, and other events and resources.

Is it worth creating a "Shows And Workshops" section or something like that, or should I try to squeeze it into the "Communities And Genres" or the "Books And References" sections?

Thank you.

**Comment by obxium** [comment]
Cool and thank you for the suggestion!

**Comment by obxium** [comment]
Added an Events section for such listings and added DAOWO to it
